### ISSUE TITLE
DEMD-database...

### ISSUE THREAD

**Issue by Kimed** [aspadm/EI-HD-tiles#1]
(пардон за оффтоп, но тот репозиторий закрыт, а ПМ здесь нету)

Не осталось ли у Вас со времен работы над DEMD-database каких-либо заметок, схем, и пр., касающихся внутреннего устройства файлов pc_resourcelib/pc_headerlib ? Меня интересует как выдрать из файлов игры текстовые данные - субтитры, емайлы, и пр. - причем желательно не пользуясь существующими тулзами, а написав собственную. Практически все, что я нашел по теме в интернете, сфокусировано больше на текстурах и моделях. Понимаю, что DEMD-database тоже в основном об этом, но все же если есть хоть какая-то информация общего характера о том, как читать эти файлы - буду благодарен за любые подсказки.

**Comment by aspadm** [comment]
Привет!
Напишите, пожалуйста, в телеграм https://t.me/aspadm
Issue удаляю, т.к. оно не относится к репозиторию
